"""
Nehemia Kaaya
CS151
Section B
Project 07 Lsis
Version 1

A set of classes and functions for buidling l-systems from scratch or from files
"""

import json
import sys

class lSys:
    """
    Returns an l-system given a base, and a dictionary of rules
    """
    def __init__(self, base: str, rules: dict[str, str]):
        self.base = base
        self.rules = rules

    def __str__(self):
        return str({'base': self.base, 'rules': self.rules})

    def addRule(self, ruleName, rule):
        self.rules[ruleName] = rule

    def getRule(self, key):
        return self.rules[key]

    def writeToFile(self, fileName="lsystem.json"):
        with open(fileName, 'w') as jsonFile:
            json.dump([self.__str__()], jsonFile, indent=4)


def createLsystemFromFile(fileName="lsystem.json", index=0):
    with open(fileName, "r") as jsonFile:
        # [{base: 'string', rules: {'initiator': 'replacement'}}]
        lSystemData = json.load(jsonFile)[index]
        if len(lSystemData) == 0:
            raise Exception("lsystem file is empty")
        return lSys(lSystemData['base'], lSystemData['rules'])


def buildString(lsys: lSys, n):
    """ Return a string generated by applying the L-system rules  
        n times"""
    result = lsys.base

    rules = lsys.rules

    for _ in range(n):
        for initiator in list(rules.keys()): # this allows us to apply multiple sets of rules 
            replacement = rules[initiator]
            result = result.replace(initiator, replacement)

    return result


def main(argv):
    if len(argv) < 3:
        print("Usage : python3 lsystem.py <in_filename> <num_iterations>")
        exit()

    lSystemFileName = argv[1]
    noOfIterations = int(argv[2])

    lSystem = createLsystemFromFile(lSystemFileName)

    finalString = buildString(lSystem, noOfIterations)

    print(finalString)

if __name__ == '__main__':
    main(sys.argv)
