"""
Nehemia Kaaya
CS 151
Section B
Project 11

Adapted from Project 08
"""

import json


class Lsystem:
    def __init__(self, fileName=None):
        self.base = ""
        self.rules = {}

        if fileName != None:
            self.read(fileName)

    def getBase(self):
        return self.base

    def setBase(self, b):
        self.base = b

    def getRule(self, initiator):
        return self.rules[initiator]

    def setRule(self, newRule):
        self.rules.update(newRule)

    def numRules(self):
        return len(self.rules)

    def buildString(self, n):
        """ Return a string generated by applying the L-system rules  
        n times"""
        result = self.base

        rules = self.rules

        for _ in range(n):
            # this allows us to apply multiple sets of rules
            for initiator in list(rules.keys()):
                replacement = rules[initiator]
                result = result.replace(initiator, replacement)

        return result

    def read(self, fileName="lsystem.json", key='SystemFL.txt'):
        with open(fileName, "r") as jsonFile:
            # {'some-key':{base: 'string', rules: {'initiator': 'replacement'}}}
            lSystemData = json.load(jsonFile)[key]
            if len(lSystemData) == 0:
                raise Exception("lsystem file is empty")

            base = lSystemData['base']
            rules = lSystemData['rules']

            self.base = base
            self.rules = rules

            jsonFile.close()

    def writeToFile(self, fileName="lsystem.json"):
        with open(fileName, 'w') as jsonFile:
            json.dump([self.__str__()], jsonFile, indent=4)

    def __str__(self):
        return str({'base': self.base, 'rules': self.rules})


def getAvailableLsystems():
    lsystemKeys = []
    with open("lsystem.json", "r") as jsonFile:
        lsystemData = json.load(jsonFile)
        lsystemKeys = list(lsystemData.keys())
        jsonFile.close()
    return lsystemKeys


def main():
    myLsys = Lsystem()
    # myLsys.setBase("F-F-F-F")
    # myLsys.setRule({
    #     "F": "F-FF--F-F"
    # })

    myLsys.read(index=1)

    print(myLsys)


if __name__ == "__main__":
    main()
